### PR TITLE
Drop column groups.team_item_id

### LINKED ISSUE #489: Get rid of `team_item_id`
## Motivations 
After #487 , team_item_id is not needed anymore.

## Tasks
* When set copy team_item_id in activity_id
* Remove `team_item_id`

### PR DESCRIPTION
**Pull request by zenovich**
Fixes #489

### CODE REVIEW

**Comment by smadbe** [comment]
I haven't started the review as the tests failed. Let me know if I have to.

**Comment by zenovich** [comment]
> I haven't started the review as the tests failed. Let me know if I have to.

fixed

**Comment by smadbe** [comment]
@zenovich :  I forgot it but can you please remove the related attribute `team_participating` as well?

**Comment by zenovich** [comment]
> @zenovich : I forgot it but can you please remove the related attribute `team_participating` as well?

done

**Pull request merged**
