### PR TITLE
Refactor time-related template functions used in cucumber tests

### PR DESCRIPTION
**Pull request by zenovich**
1. Rename template functions used in cucumber tests for clarity:
- relativeTime -> relativeTimeDB (returns time relative to the current time in the DB format),
- timeToRFC -> timeDBToJS (converts time from DB format to JS format).
2. Add support for nanoseconds in timeDBToJS (will be used in next PRs).
3. Add a new function relativeTimeDBMs (similar to relativeTimeDB, but with milliseconds; will be used in next PRs).
4. Add new functions currentTimeDB & currentTimeDBMs returning the current time in the DB format (with and without milliseconds; will be used in next PRs).

### CODE REVIEW

**Comment by zenovich** [comment]
fyi, @GeoffreyHuck

**Review by smadbe — APPROVED** [review]

**Review by smadbe — CHANGES_REQUESTED** [review]
Hum actually

> timeToRFC -> timeDBToJS (converts time from DB format to JS format).

It is not really a JS format. It converts the DB format to the RFCxyc format.

**Comment by smadbe** [comment]
or iso8601 or just string format, but "JS format" makes no sense to me.

**Comment by zenovich** [comment]
> Hum actually
> 
> > timeToRFC -> timeDBToJS (converts time from DB format to JS format).
> 
> It is not really a JS format. It converts the DB format to the RFCxyc format.

I know, but in the context of our cucumber tests it is the format we in our JSON response for time values. It's not clear which function to use and where. It's pain. I think the timeDBToJS is clearer, but maybe there are other options. There are lots of RFCs anyway.

**Comment by zenovich** [comment]
It will be timeDBToRFC()

**Comment by smadbe** [comment]
That's correct that RFC alone does not mean anything, it is  RFC 3339 for the date time format.

**Comment by zenovich** [comment]
Can I rename it into timeDBToRFC3339 later in separate PR?

**Review by smadbe — APPROVED** [review]
> Can I rename it into timeDBToRFC3339 later in a separate PR?

I don't see the point, but yes

**Pull request merged**
