### PR TITLE
Logging reorg ++

### PR DESCRIPTION
**Pull request by smadbe**
The global goal was to reorganize the logging so that it can be stored in a log file instead of outputting it to stderr. 
Many related had to be fixed to have something proper:
- cleaner way to log
- multiple formats for logging
- 100% test coverage for logging
- db logger working correctly
- saner config for logging
- use local config file to allow each dev to have its own config

To be reviewed commit per commit, should be quite clean.

### CODE REVIEW

**Comment by zenovich** [comment]
It looks like the logger escapes color sequences in default output: ```=== RUN   TestBase_SetQueryLimit/with_limit
level=info msg="\x1b[35m(/Users/dzenovich/gowork/src/github.com/France-ioi/AlgoreaBackend/app/database/db.go:158)\x1b[0m \n\x1b[33m[2019-03-04 12:20:11]\x1b[0m  \x1b[36;1m[1.60ms]\x1b[0m  SELECT * FROM `users`   LIMIT 10  \n\x1b[36;31m[0 rows affected or returned ]\x1b[0m "
=== RUN   TestBase_SetQueryLimit/without_limit
level=info msg="\x1b[35m(/Users/dzenovich/gowork/src/github.com/France-ioi/AlgoreaBackend/app/database/db.go:158)\x1b[0m \n\x1b[33m[2019-03-04 12:20:11]\x1b[0m  \x1b[36;1m[6.63ms]\x1b[0m  SELECT * FROM `users`   LIMIT 500  \n\x1b[36;31m[0 rows affected or returned ]\x1b[0m "
=== RUN   TestBase_SetQueryLimit/wrong_limit
level=info msg="\x1b[35m(/Users/dzenovich/gowork/src/github.com/France-ioi/AlgoreaBackend/app/database/db.go:158)\x1b[0m \n\x1b[33m[2019-03-04 12:20:11]\x1b[0m  \x1b[36;1m[0.83ms]\x1b[0m  SELECT * FROM `users`   LIMIT 500  \n\x1b[36;31m[0 rows affected or returned ]\x1b[0m "
--- PASS: TestBase_SetQueryLimit (0.05s)```

**Comment by zenovich** [comment]
Probably, it would be better to use a format like ```

**Comment by smadbe** [comment]
> Probably, it would be better to use a format like
> 
> ```
> [2017-06-22 19:52:11 +0300] INFO : ...
> ```

For the console version of the log? For now, I haven't invested time in formatting, I just reused the existing formatter. These colored formats are supposed to be nice but I understand that it may be better to have something consistent. Anyway as you don't mind it is mixed with tests outputs (both `go-test` and gherkins), more or less unformat should not be a problem 😄. More seriously, it is a matter of writing another (simple) formatter. It may be done but it will be in another PR.

**Comment by zenovich** [comment]
> > Probably, it would be better to use a format like
> > ```
> > [2017-06-22 19:52:11 +0300] INFO : ...
> > ```
> 
> For the console version of the log? For now, I haven't invested time in formatting, I just reused the existing formatter. These colored formats are supposed to be nice but I understand that it may be better to have something consistent. Anyway as you don't mind it is mixed with tests outputs (both `go-test` and gherkins), more or less unformat should not be a problem 😄. More seriously, it is a matter of writing another (simple) formatter. It may be done but it will be in another PR.

At least we need something like 
```
INFO: ...
```
because the current default format (level=info msg="...") contains non-informative words (level, msg) and escapes messages making them unreadable

**Comment by smadbe** [comment]
Should be fixed now. I don't really understand why it didn't detect it was a TTY to display color but now it works. Alternative format may be used, but I think that at least this is better than before for both text-in-termal and json-in-file cases

**Pull request merged**
