### PR TITLE
Remove aliases for imports

### PR DESCRIPTION
**Pull request by slomek**
Aliasing is not necessary unless we have multiple imports that share their name.

### CODE REVIEW

**Comment by slomek** [comment]
I get your point, so I reverted the changes regarding assert library 👍

**Comment by smadbe** [comment]
good for me. are you able to merge?

**Comment by slomek** [comment]
Nope, I get _Merging is blocked_ and _The base branch restricts merging to authorized users._

**Comment by smadbe** [comment]
better now?

**Comment by slomek** [comment]
Yup 🙂

**Pull request merged**
